### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Neek0o00** [groupnoto/rd#18]

**Comment by joshakinsola** [comment]
@cuddeford please see me so we can create a high fidelity prototype based on my sketches

**Comment by Neek0o00** [comment]
![img_0654](https://cloud.githubusercontent.com/assets/9210880/6128527/9046ebd6-b12e-11e4-9439-ff6e46e02c36.jpeg)
![img_0716](https://cloud.githubusercontent.com/assets/9210880/6128532/906bba24-b12e-11e4-9af0-76f2fba8e200.jpeg)
![img_1219](https://cloud.githubusercontent.com/assets/9210880/6128529/90693844-b12e-11e4-8f2b-5ed96e21d198.jpeg)
![img_1351](https://cloud.githubusercontent.com/assets/9210880/6128530/90697c64-b12e-11e4-823b-0e5d210cb1b5.jpeg)
![img_1797](https://cloud.githubusercontent.com/assets/9210880/6128531/906b2f14-b12e-11e4-9643-7b51f4c91b7c.jpeg)
![img_4844](https://cloud.githubusercontent.com/assets/9210880/6128533/906d2936-b12e-11e4-881d-d89db49daf0b.jpeg)
![img_6212](https://cloud.githubusercontent.com/assets/9210880/6128528/905e01cc-b12e-11e4-9845-2290f36723a7.jpeg)
![img_7990](https://cloud.githubusercontent.com/assets/9210880/6128534/9075eb98-b12e-11e4-8db9-ae25fc95594a.jpeg)
