### ISSUE TITLE
Gestures mockups 

### ISSUE THREAD

**Issue by joshakinsola** [groupnoto/rd#7]
Work with requirements to get this done

**Comment by Neek0o00** [comment]
![img_1351](https://cloud.githubusercontent.com/assets/9210880/6128886/b231d2ee-b131-11e4-9646-27b106ae75ac.jpeg)
![img_7990](https://cloud.githubusercontent.com/assets/9210880/6128885/b22b41ae-b131-11e4-99c7-6209c366124a.jpeg)
